# Generated by Django 4.2 on 2024-11-27 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('단순조회중', '단순조회중'), ('신용조회중', '신용조회중'), ('서류수취중', '서류수취중'), ('심사중', '심사중'), ('승인', '승인'), ('자서예정', '자서예정'), ('기표예정', '기표예정'), ('용도증빙', '용도증빙'), ('완료', '완료')], default='단순조회중', max_length=20, null=True, verbose_name='진행상황')),
                ('referrer', models.CharField(blank=True, max_length=50, null=True, verbose_name='레퍼')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일')),
                ('borrower_name', models.CharField(max_length=50, verbose_name='차주명')),
                ('borrower_birth', models.CharField(blank=True, max_length=6, null=True, verbose_name='차주 생년월일')),
                ('borrower_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='차주 연락처')),
                ('borrower_credit_score', models.IntegerField(blank=True, null=True, verbose_name='차주 신용점수')),
                ('address_main', models.CharField(blank=True, help_text='동까지', max_length=200, null=True, verbose_name='담보물건지')),
                ('address_detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='상세주소')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='면적')),
                ('is_lower_than_2nd', models.BooleanField(blank=True, default=False, null=True, verbose_name='2층이하')),
                ('is_commercial_residential', models.BooleanField(blank=True, default=False, null=True, verbose_name='주상복합')),
                ('is_above_4th_rank', models.BooleanField(blank=True, default=False, null=True, verbose_name='4순위이상')),
                ('has_registration_issue', models.BooleanField(blank=True, default=False, null=True, verbose_name='등기이상')),
                ('is_trading_price_low', models.BooleanField(blank=True, default=False, null=True, verbose_name='실거래가열위')),
                ('price_type', models.CharField(blank=True, choices=[('KB일반가', 'KB일반가'), ('KB하한가', 'KB하한가'), ('테크가', '테크가'), ('탁감가', '탁감가'), ('정감가', '정감가')], max_length=20, null=True, verbose_name='시세구분')),
                ('price_amount', models.IntegerField(blank=True, help_text='단위: 만원', null=True, verbose_name='시세금액')),
                ('business_type', models.CharField(blank=True, choices=[('일반', '일반'), ('간이', '간이'), ('면세', '면세'), ('법인', '법인')], max_length=10, null=True, verbose_name='사업자구분')),
                ('monthly_sales', models.IntegerField(blank=True, help_text='단위: 만원', null=True, verbose_name='현재매출')),
                ('vat_status', models.CharField(blank=True, choices=[('신고함-정상', '신고함-정상'), ('신고필요-기한후', '신고필요-기한후'), ('신고필요-수정', '신고필요-수정'), ('신고필요-대행', '신고필요-대행'), ('거절의사', '거절의사')], max_length=20, null=True, verbose_name='부가세 신고 여부')),
                ('other_income', models.CharField(blank=True, max_length=200, null=True, verbose_name='사업자외소득')),
                ('is_fake_business', models.BooleanField(blank=True, default=False, null=True, verbose_name='가라사업자 여부')),
                ('is_soho', models.BooleanField(blank=True, default=False, null=True, verbose_name='소호여부')),
                ('need_proof_of_use', models.BooleanField(blank=True, default=False, null=True, verbose_name='용도증빙필요')),
                ('is_separate_household', models.BooleanField(blank=True, default=False, null=True, verbose_name='별도세대')),
                ('residents', models.TextField(blank=True, null=True, verbose_name='거주구성원')),
                ('loan_amount', models.IntegerField(blank=True, help_text='단위: 만원', null=True, verbose_name='실행금액')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='실행금리')),
                ('is_urgent', models.BooleanField(default=False)),
                ('waiting_for_reference_response', models.BooleanField(default=False)),
                ('reception_date', models.DateField(blank=True, null=True)),
                ('authorizing_date', models.DateField(blank=True, null=True)),
                ('journalizing_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('status_changes', models.JSONField(blank=True, default=list, null=True, verbose_name='상태 변경 이력')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '대출건',
                'verbose_name_plural': '대출건 목록',
            },
        ),
        migrations.CreateModel(
            name='SecurityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('birth_date', models.CharField(blank=True, max_length=6, null=True, verbose_name='생년월일')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='연락처')),
                ('credit_score', models.IntegerField(blank=True, null=True, verbose_name='신용점수')),
                ('relationship_type', models.CharField(blank=True, choices=[('spouse', '배우자'), ('parent', '부모님'), ('sibling', '형제/자매'), ('child', '자녀'), ('other', '기타')], max_length=20, null=True, verbose_name='관계 유형')),
                ('loan_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_providers', to='core.loancase', verbose_name='대출 건')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='core.securityprovider', verbose_name='연관된 제공자')),
            ],
            options={
                'verbose_name': '담보제공자',
                'verbose_name_plural': '담보제공자 목록',
            },
        ),
        migrations.CreateModel(
            name='PriorLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('선설정', '선설정'), ('대환', '대환')], max_length=10, verbose_name='구분')),
                ('financial_company', models.CharField(max_length=50, verbose_name='금융사')),
                ('amount', models.IntegerField(help_text='단위: 만원', verbose_name='금액')),
                ('loan_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_loans', to='core.loancase', verbose_name='대출 건')),
            ],
            options={
                'verbose_name': '선설정/대환 대출',
                'verbose_name_plural': '선설정/대환 대출 목록',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('priority', models.CharField(blank=True, choices=[('높음', '높음'), ('중간', '중간'), ('낮음', '낮음')], default='중간', max_length=10, null=True, verbose_name='중요도')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='게시 종료일')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 목록',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='상담내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulting_logs', to=settings.AUTH_USER_MODEL)),
                ('loan_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulting_logs', to='core.loancase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일시')),
                ('is_question', models.BooleanField(blank=True, default=False, null=True, verbose_name='관리자 질문여부')),
                ('is_read', models.BooleanField(blank=True, default=False, null=True, verbose_name='읽음여부')),
                ('loan_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.loancase')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.casecomment', verbose_name='상위 댓글')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '케이스 댓글',
                'verbose_name_plural': '케이스 댓글 목록',
                'ordering': ['created_at'],
            },
        ),
    ]
