# Generated by Django 4.2 on 2024-11-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('authorizing_date', models.DateField(blank=True, null=True, verbose_name='자서예정일')),
                ('journalizing_date', models.DateField(blank=True, null=True, verbose_name='기표예정일')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='고객요청일')),
            ],
        ),
        migrations.AlterField(
            model_name='loancase',
            name='authorizing_date',
            field=models.DateField(blank=True, null=True, verbose_name='자서예정일'),
        ),
        migrations.AlterField(
            model_name='loancase',
            name='journalizing_date',
            field=models.DateField(blank=True, null=True, verbose_name='기표예정일'),
        ),
        migrations.AlterField(
            model_name='loancase',
            name='reception_date',
            field=models.DateField(blank=True, null=True, verbose_name='접수일'),
        ),
        migrations.AlterField(
            model_name='loancase',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='고객요청일'),
        ),
    ]
