# Generated by Django 4.2 on 2024-11-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_alter_loancase_authorizing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='loan_case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.loancase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='authorizing_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='자서예정일'),
        ),
        migrations.AlterField(
            model_name='event',
            name='journalizing_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='기표예정일'),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduled_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='고객요청일'),
        ),
    ]
