# Generated by Django 4.2 on 2024-12-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_loan_case_alter_event_authorizing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='authorizing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='journalizing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loancase',
            name='borrower_name',
            field=models.CharField(max_length=255),
        ),
    ]
