# Generated by Django 4.2 on 2024-12-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_authorizing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancase',
            name='status',
            field=models.CharField(blank=True, choices=[('단순조회중', '단순조회중'), ('신용조회중', '신용조회중'), ('서류수취중', '서류수취중'), ('심사중', '심사중'), ('승인', '승인'), ('자서예정', '자서예정'), ('기표예정', '기표예정'), ('용도증빙', '용도증빙'), ('완료', '완료'), ('취소', '취소'), ('거절', '거절'), ('보류', '보류')], default='단순조회중', max_length=20, null=True, verbose_name='진행상황'),
        ),
    ]
