# Generated by Django 4.2 on 2024-12-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_authorizing_date_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancase',
            name='business_type',
            field=models.CharField(blank=True, choices=[('일반(실)', '일반(실)'), ('일반(가)', '일반(가)'), ('간이(실)', '간이(실)'), ('간이(가)', '간이(가)'), ('면세', '면세'), ('법인', '법인')], max_length=10, null=True, verbose_name='사업자구분'),
        ),
    ]
