# Generated by Django 4.2 on 2024-12-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_loancase_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancase',
            name='business_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='업태'),
        ),
        migrations.AddField(
            model_name='loancase',
            name='business_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='종목'),
        ),
        migrations.AddField(
            model_name='loancase',
            name='business_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자번호'),
        ),
        migrations.AddField(
            model_name='loancase',
            name='introducer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='소개자'),
        ),
        migrations.AddField(
            model_name='loancase',
            name='is_tenant',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='세입자'),
        ),
        migrations.AddField(
            model_name='loancase',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('신규', '신규'), ('추가', '추가'), ('대환', '대환')], max_length=10, null=True, verbose_name='대출 유형'),
        ),
    ]
