# Generated by Django 4.2 on 2024-12-28 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_loancase_business_category_loancase_business_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='마감일')),
                ('status', models.CharField(choices=[('pending', '대기'), ('in_progress', '진행중'), ('completed', '완료')], default='pending', max_length=20, verbose_name='상태')),
                ('priority', models.IntegerField(choices=[(1, '낮음'), (2, '보통'), (3, '높음')], default=2, verbose_name='우선순위')),
                ('is_archived', models.BooleanField(default=False, verbose_name='보관 여부')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_todos', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_todos', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('loan_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='core.loancase', verbose_name='대출 건')),
            ],
            options={
                'verbose_name': '할일',
                'verbose_name_plural': '할일 목록',
                'ordering': ['-priority', 'deadline', '-created_at'],
            },
        ),
    ]
