# Generated by Django 4.2 on 2024-12-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todotemplate_todohistory'),
    ]

    operations = [
    ]
